"""
Schemas Pydantic for the /conversation endpoint of the API.

Defines the request and response models for the queries
made to the RAG system through the REST API and Retell AI.
"""

from typing import List, Optional, Dict, Any

from pydantic import BaseModel, Field
from utils.config import settings


class SearchRequest(BaseModel):
    """Specific arguments of the tool (inside 'args').
    
    Attributes:
        query: User's question about the document.
    """

    query: str = Field(..., description="User's question", min_length=2)
    top_k: int = Field(default=settings.top_k, description="Number of relevant documents to consider", ge=1, le=15)


class SourceInfo(BaseModel):
    """Information about a source document in the response.

    Attributes:
        content: Relevant extract from the document.
        source: Source file.
        page: Page number of the document.
    """

    content: str = Field(..., description="Relevant extract from the document")
    source: str = Field(..., description="Source file")
    page: int = Field(..., description="Page number of the document")


class SearchResponse(BaseModel):
    """Response body for the /ask endpoint.

    Attributes:
        query: The original question.
        answer: Answer generated by the model.
        sources: Source documents used for the answer.
        error: Error message in case of failure.
    """

    query: str = Field(..., description="Original question")
    answer: str = Field(..., description="Answer generated by the model")
    sources: List[SourceInfo] = Field(
        default_factory=list, description="Source documents"
    )
    error: Optional[str] = Field(default=None, description="Error message")