"""
Pydantic schemas for RAG system responses.

Defines the response models returned by the pipeline
when processing queries against the knowledge base.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class SourceDocument(BaseModel):
    """Referenced source document in a response.

    Attributes:
        content: Extract of the document content.
        source: Path to the source file.
        page: Page number where the information was found.
    """

    content: str = Field(..., description="Extracto del contenido")
    source: str = Field(..., description="Path to the source file")
    page: int = Field(..., description="Page number")


class RAGResponse(BaseModel):
    """RAG system response to a query.

    Attributes:
        query: The original user query.
        answer: Response generated by the model.
        sources: List of source documents used.
        error: Error message in case of failure (None if no error).
    """

    query: str = Field(..., description="Original user query")
    answer: str = Field(..., description="Generated response")
    sources: List[SourceDocument] = Field(
        default_factory=list, description="Source documents used"
    )
    error: Optional[str] = Field(
        default=None, description="Error message if failure occurred"
    )
